services:
  dnsdist:
    image: powerdns/dnsdist-19:1.9.6
    container_name: dnsdist
    volumes:
      - ./dnsdist:/etc/dnsdist/
    restart: unless-stopped
    ports:
      - "443:443/tcp"
      - "853:853/tcp"
      - "443:443/udp"
    networks:
      dns_network:
        ipv4_address: 172.16.0.4

networks:
   dns_network:
     external: true

